services:
  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    container_name: flask-dev
    build: .
    ports:
      - 5000:5000